spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/dentistry?serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
management:
  endpoint:
    restart:
      enabled: true